[build]
target = "xtensa-esp32-espidf"

# Override for tests to use host target
[target.x86_64-unknown-linux-gnu]
runner = "echo 'Running test on host target'"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
# runner = "espflash --monitor" # Uncomment to flash directly to hardware

[unstable]
build-std = ["std", "panic_abort"]

[env]
# Note: these variables are not used by the build
# They are here for documentation purposes
ESP_IDF_VERSION = "5.1.2"
ESP_IDF_TOOLS_INSTALL_DIR = { value = "~/.espressif" }
ESP_IDF_PYTHON_ENV_PATH = { value = "~/.espressif/python_env/idf5.1_py3.8_env" }

# Builds requiring std for ESP-IDF
[target.xtensa-esp32-espidf.env]
ESP_IDF_SDKCONFIG_DEFAULTS = "sdkconfig.defaults"